### ISSUE TITLE
CMake zlib handling

### ISSUE THREAD

**Issue by jpd002** [jpd002/Play-Dependencies#6]
@Thunder07 Just so you know, I'm looking at the way zlib is used in the new CMake projects. I saw you had to change the `CMakeLists.txt` file from the zlib distribution and I'm trying to see if there would be a way to use zlib in the projects without altering zlib's source.

Branches:
https://github.com/jpd002/Play-Dependencies/tree/zlib-test
https://github.com/jpd002/Play-/tree/zlib-test

**Comment by Zer0xFF** [comment]
for the most part, it can be left as is, you'd just need to declare `SKIP_INSTALL_ALL` in `Play!`'s `CMakeLists.txt`. (I decided to remove that part of the code since I didn't imagine their will be much need for it vs needing to declare that anywhere zlib needs to be built, as I have with glew)
the other change i made was for the headers, since cmake will make a new header and copy it to the build directory, I needed an easier way to be able to find it, since the build directory can be different depending on whether you're building `Framework`, `Play!` or `PsfPlayer`, you can also work around this by changing the `CMakeLists.txt` script to create the new header in place of the old one instead of in the build directory.

**Comment by jpd002** [comment]
Oh yeah, I see what you mean now. The `CMakeLists.txt` file provided by zlib is kinda useless for us since it deletes the `zconf.h` file, which would be ok if we had a single `CMakeLists.txt` on our side. Anyways, I've created a [new one with the bare minimum](https://github.com/jpd002/Play-Dependencies/blob/master/build_cmake/zlib-1.2.8/CMakeLists.txt).

I also made sure the system's zlib is used when it's available (which should be the case everywhere except for MSVC/Win32).
